# Site settings
title: A Day In The Woods
email: nthompson55@gmail.com
description: >
  Nate Thompson's blog on a variety of topics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "blog.felttrip.com" # the base hostname & protocol for your site
bitcoin: "3HzpgZukKCjpJxkYyETzFFWFPjW52neqYZ"
linkedin_username: thompsonnathaniel
github_username: felttrip
author: by Nate Thompson
# Build settings
markdown: kramdown
future: true
